### ISSUE TITLE
Cannot hide android status bar

### ISSUE THREAD

**Issue by arstiefel** [jineshshah36/react-native-nav#11]
I am trying to hide the android status bar but `hidden: true` does not work

**Comment by gcushen** [comment]
You can hide the status bar _contents_ on Android using something like the following (it's working for me with react-native-nav v1.1.4). It would be nice if these more advanced things were added to the example project code though. 

Note that this code appears to hide the _contents_ of the status bar and overlay the `backgroundColor`, rather than actually removing the status bar from view. I don't know if this is a bug or by design?

```
render () {  
  var StatusBarConfig = {
      hidden: true,
    };

      return(
        <NavBar statusBar={StatusBarConfig}>
          <NavTitle>
            {"StatusBar Hidden"}
          </NavTitle>
        </NavBar>
);
}
```
